function R = plotPosterMarkerTimeSeries(trialData, markerNames, videoID, varargin)
% plotPosterMarkerTimeSeries - Poster-friendly positional time series for marker trajectories.
%
% Usage:
%   plotPosterMarkerTimeSeries(trialData, 'LFHD', 'vid01')
%   plotPosterMarkerTimeSeries(trialData, {'LFHD','RFHD'}, 'vid01', 'dimension', 'z')
%
% Inputs:
%   trialData   - struct with markerNames, trajectoryData, and metaData (or pass mocapMetaData)
%   markerNames - marker name or list of marker names
%   videoID     - stimulus/video identifier
%
% Name-value pairs:
%   'dimension'              - 'x' (default), 'y', 'z', or 1/2/3
%   'mocapMetaData'          - metadata struct (default trialData.metaData)
%   'plotWhere'              - axes handle (default: new figure/axes)
%   'figureTitle'            - custom title (default autogenerated)
%   'xLabel'                 - custom x-axis label (default based on time units)
%   'yLabel'                 - custom y-axis label (default based on dimension)
%   'invertYAxis'            - reverse position panel y-axis direction (default false)
%   'relativePositionMarker' - subtract this marker trajectory before plotting (default none)
%   'showAverageTrajectory'  - plot average across selected markers only (default false)
%   'verticalOffset'         - scalar offset applied per marker index (default 0)
%   'smoothWindowFrames'     - moving average window in frames (default 1 = none)
%   'clipSec'                - clip from start of stimulus segment (default 0)
%   'timeUnits'              - 'seconds' (default) or 'frames'
%   'normalizeTimeToZero'    - start x-axis at 0 (default true)
%   'lineWidth'              - line width (default 2.2)
%   'lineAlpha'              - scalar [0..1], if supported (default 1)
%   'colors'                 - nMarkers x 3 color matrix or [] for auto
%   'legendLocation'         - legend location (default 'best')
%   'legendFontSize'         - legend font size (default 12)
%   'showLegend'             - logical (default true if multiple traces)
%   'gridOn'                 - logical (default true)
%   'showSpeedPanel'         - add lower panel with instantaneous speed (default false)
%   'speedWindowSec'         - sliding window for speed calc in seconds (default 0.1)
%   'speedShowAverage'       - overlay average speed across markers (default true)
%   'speedColors'            - nLines x 3 color matrix for speed traces or [] for auto
%   'showImmobileShading'    - shade intervals where avg speed < threshold (default true)
%   'immobileSpeedThreshold' - speed threshold in mm/s (default 25)
%   'immobileMinDurationSec' - minimum immobile bout duration to shade (default 1)
%   'immobileShadeColor'     - RGB color for shaded boxes (default [0.75 0.75 0.75])
%   'immobileShadeAlpha'     - shading alpha (default 0.22)
%   'savePath'               - file path to export figure (default '')
%
% Output:
%   R - struct with fields figure, axes, lineHandles, extracted, dimensionIndex

    p = inputParser;
    addRequired(p, 'trialData', @isstruct);
    addRequired(p, 'markerNames', @(x) ischar(x) || isstring(x) || iscell(x));
    addRequired(p, 'videoID', @(x) ischar(x) || isstring(x));
    addParameter(p, 'dimension', 'x');
    addParameter(p, 'mocapMetaData', struct(), @isstruct);
    addParameter(p, 'plotWhere', [], @(x) isempty(x) || isgraphics(x, 'axes'));
    addParameter(p, 'figureTitle', '', @(x) ischar(x) || isstring(x));
    addParameter(p, 'xLabel', '', @(x) ischar(x) || isstring(x));
    addParameter(p, 'yLabel', '', @(x) ischar(x) || isstring(x));
    addParameter(p, 'invertYAxis', false, @(x) islogical(x) && isscalar(x));
    addParameter(p, 'relativePositionMarker', '', @(x) ischar(x) || isstring(x));
    addParameter(p, 'showAverageTrajectory', false, @(x) islogical(x) && isscalar(x));
    addParameter(p, 'verticalOffset', 0, @(x) isnumeric(x) && isscalar(x));
    addParameter(p, 'smoothWindowFrames', 1, @(x) isnumeric(x) && isscalar(x) && x >= 1);
    addParameter(p, 'clipSec', 0, @(x) isnumeric(x) && isscalar(x) && x >= 0);
    addParameter(p, 'timeUnits', 'seconds', @(x) ischar(x) || isstring(x));
    addParameter(p, 'normalizeTimeToZero', true, @(x) islogical(x) && isscalar(x));
    addParameter(p, 'lineWidth', 2.2, @(x) isnumeric(x) && isscalar(x) && x > 0);
    addParameter(p, 'lineAlpha', 1, @(x) isnumeric(x) && isscalar(x) && x > 0 && x <= 1);
    addParameter(p, 'colors', [], @(x) isempty(x) || isnumeric(x));
    addParameter(p, 'legendLocation', 'best', @(x) ischar(x) || isstring(x));
    addParameter(p, 'legendFontSize', 12, @(x) isnumeric(x) && isscalar(x) && x > 0);
    addParameter(p, 'showLegend', [], @(x) isempty(x) || (islogical(x) && isscalar(x)));
    addParameter(p, 'gridOn', true, @(x) islogical(x) && isscalar(x));
    addParameter(p, 'showSpeedPanel', true, @(x) islogical(x) && isscalar(x));
    addParameter(p, 'speedWindowSec', 0.1, @(x) isnumeric(x) && isscalar(x) && x > 0);
    addParameter(p, 'speedShowAverage', true, @(x) islogical(x) && isscalar(x));
    addParameter(p, 'speedColors', [], @(x) isempty(x) || isnumeric(x));
    addParameter(p, 'showImmobileShading', true, @(x) islogical(x) && isscalar(x));
    addParameter(p, 'immobileSpeedThreshold', 25, @(x) isnumeric(x) && isscalar(x) && x >= 0);
    addParameter(p, 'immobileMinDurationSec', 1, @(x) isnumeric(x) && isscalar(x) && x >= 0);
    addParameter(p, 'immobileShadeColor', [0.75 0.75 0.75], @(x) isnumeric(x) && numel(x) == 3);
    addParameter(p, 'immobileShadeAlpha', 0.22, @(x) isnumeric(x) && isscalar(x) && x >= 0 && x <= 1);
    addParameter(p, 'savePath', '', @(x) ischar(x) || isstring(x));
    parse(p, trialData, markerNames, videoID, varargin{:});

    markerNames = cellstr(string(markerNames));
    videoID = char(string(videoID));
    dimIdx = localResolveDimension(p.Results.dimension);
    dimLabel = upper(char('x' + (dimIdx-1))); % X, Y, Z

    extracted = extractMarkerTrajectoryForVideo( ...
        trialData, markerNames, videoID, ...
        'mocapMetaData', p.Results.mocapMetaData, ...
        'clipSec', p.Results.clipSec);

    data = extracted.trajectories;
    rawLabels = extracted.markerNames;

    % Optionally convert to positions relative to another marker.
    refMarker = char(string(p.Results.relativePositionMarker));
    if ~isempty(strtrim(refMarker))
        refExtracted = extractMarkerTrajectoryForVideo( ...
            trialData, refMarker, videoID, ...
            'mocapMetaData', p.Results.mocapMetaData, ...
            'clipSec', p.Results.clipSec);
        refTraj = refExtracted.trajectories(:, :, 1);
        for m = 1:size(data, 3)
            data(:, :, m) = data(:, :, m) - refTraj;
        end
    end

    y = squeeze(data(:, dimIdx, :));  % nFrames x nMarkers (or nFrames x 1)
    if isvector(y)
        y = y(:);
    end
    labels = rawLabels;

    if p.Results.showAverageTrajectory && size(y, 2) > 1
        y = mean(y, 2, 'omitnan');
        labels = {'Average trajectory'};
    elseif p.Results.showAverageTrajectory && size(y, 2) == 1
        labels = {'Average trajectory'};
    end

    smoothWin = round(p.Results.smoothWindowFrames);
    if smoothWin > 1
        for c = 1:size(y, 2)
            y(:, c) = movmean(y(:, c), smoothWin, 'omitnan');
        end
    end

    x = localBuildX(extracted, p.Results.timeUnits, p.Results.normalizeTimeToZero);

    % Compute marker speeds / average speed when needed for speed panel and/or immobility shading.
    markerSpeeds = [];
    avgSpeed = [];
    immobileMask = [];
    needsSpeed = p.Results.showSpeedPanel || p.Results.showImmobileShading;
    if needsSpeed
        if isempty(extracted.frameRate)
            if p.Results.showSpeedPanel
                error('plotPosterMarkerTimeSeries:MissingFrameRateForSpeed', ...
                    'Cannot compute speed panel because frame rate is missing in metadata.');
            else
                warning('plotPosterMarkerTimeSeries:MissingFrameRateForImmobility', ...
                    'Frame rate missing; skipping immobility shading.');
            end
        else
            nMarkersRaw = size(data, 3);
            markerSpeeds = nan(size(data, 1), nMarkersRaw);
            for m = 1:nMarkersRaw
                markerSpeeds(:, m) = getTrajectorySpeed(data(:, :, m), extracted.frameRate, p.Results.speedWindowSec);
            end
            avgSpeed = mean(markerSpeeds, 2, 'omitnan');
            immobileMask = getImmobileFramesFromSpeed(avgSpeed, extracted.frameRate, ...
                'thresholdMmPerSec', p.Results.immobileSpeedThreshold, ...
                'minDurationSec', p.Results.immobileMinDurationSec);
        end
    end

    if p.Results.verticalOffset ~= 0 && size(y, 2) > 1
        for c = 1:size(y, 2)
            y(:, c) = y(:, c) + (c-1) * p.Results.verticalOffset;
        end
    end

    ax = p.Results.plotWhere;
    speedAx = [];
    if p.Results.showSpeedPanel && ~isempty(ax)
        error('plotPosterMarkerTimeSeries:PlotWhereWithSpeedPanel', ...
            'showSpeedPanel=true is not supported when ''plotWhere'' is provided.');
    end

    if isempty(ax)
        fig = figure('Color', 'w');
        if p.Results.showSpeedPanel
            tl = tiledlayout(fig, 2, 1, 'TileSpacing', 'compact', 'Padding', 'compact');
            ax = nexttile(tl, 1);
            speedAx = nexttile(tl, 2);
        else
            ax = axes('Parent', fig);
        end
    else
        fig = ancestor(ax, 'figure');
    end

    hold(ax, 'on');
    colors = localResolveColors(size(y, 2), p.Results.colors);
    hLines = gobjects(size(y, 2), 1);
    for c = 1:size(y, 2)
        thisColor = colors(c, :);
        thisLineWidth = p.Results.lineWidth;
        if c == 1
            thisColor = [0 0 0];
            thisLineWidth = p.Results.lineWidth + 1.0;
        end
        hLines(c) = plot(ax, x, y(:, c), ...
            'LineWidth', thisLineWidth, ...
            'Color', thisColor, ...
            'DisplayName', labels{c});
        if p.Results.lineAlpha < 1
            try
                hLines(c).Color(4) = p.Results.lineAlpha; %#ok<TRYNC>
            end
        end
    end

    immobilePatchHandles = gobjects(0);
    localApplyPosterAxesStyle(ax, p.Results.gridOn);
    if p.Results.showImmobileShading && ~isempty(immobileMask)
        immobilePatchHandles = localShadeBooleanSpans( ...
            ax, x, immobileMask, p.Results.immobileShadeColor, p.Results.immobileShadeAlpha);
        uistack(hLines, 'top');
    end

    xLabelStr = char(string(p.Results.xLabel));
    if isempty(strtrim(xLabelStr))
        if strcmpi(char(string(p.Results.timeUnits)), 'frames')
            xLabelStr = 'Frame';
        else
            xLabelStr = 'Time (s)';
        end
    end
    yLabelStr = char(string(p.Results.yLabel));
    if isempty(strtrim(yLabelStr))
        yLabelStr = sprintf('%s position (mm)', dimLabel);
        if ~isempty(strtrim(refMarker))
            yLabelStr = sprintf('%s position (relative, mm)', dimLabel);
        end
    end
    xlabel(ax, xLabelStr, 'FontSize', 12, 'FontWeight', 'bold');
    ylabel(ax, yLabelStr, 'FontSize', 12, 'FontWeight', 'bold');
    if p.Results.invertYAxis
        set(ax, 'YDir', 'reverse');
    else
        set(ax, 'YDir', 'normal');
    end

    titleStr = char(string(p.Results.figureTitle));
    if isempty(strtrim(titleStr))
        markerLabel = strjoin(markerNames, ', ');
        if p.Results.showAverageTrajectory && numel(markerNames) > 1
            markerLabel = sprintf('Average of %d markers', numel(markerNames));
        end
        titleStr = sprintf('%s | %s | %s', videoID, markerLabel, dimLabel);
    end
    title(ax, titleStr, 'Interpreter', 'none', 'FontSize', 13, 'FontWeight', 'bold');

    showLegend = p.Results.showLegend;
    if isempty(showLegend)
        showLegend = (size(y, 2) > 1);
    end
    if showLegend
        lgd = legend(ax, 'show', 'Location', char(string(p.Results.legendLocation)), 'Interpreter', 'none');
        set(lgd, 'FontSize', p.Results.legendFontSize);
    end

    speedLineHandles = gobjects(0);
    speedAvgHandle = gobjects(0);
    immobileSpeedPatchHandles = gobjects(0);
    if p.Results.showSpeedPanel
        hold(speedAx, 'on');
        speedColors = localResolveColors(size(markerSpeeds, 2), p.Results.speedColors);
        speedLineHandles = gobjects(size(markerSpeeds, 2), 1);
        for m = 1:size(markerSpeeds, 2)
            speedLineHandles(m) = plot(speedAx, x, markerSpeeds(:, m), ...
                'LineWidth', max(1.2, p.Results.lineWidth - 0.5), ...
                'Color', speedColors(m, :), ...
                'DisplayName', sprintf('%s speed', rawLabels{m}));
        end
        if p.Results.speedShowAverage && size(markerSpeeds, 2) > 1
            speedAvgHandle = plot(speedAx, x, avgSpeed, ...
                'k-', 'LineWidth', p.Results.lineWidth + 0.3, ...
                'DisplayName', 'Average speed');
        end
        localApplyPosterAxesStyle(speedAx, p.Results.gridOn);
        if p.Results.showImmobileShading && ~isempty(immobileMask)
            immobileSpeedPatchHandles = localShadeBooleanSpans( ...
                speedAx, x, immobileMask, p.Results.immobileShadeColor, p.Results.immobileShadeAlpha);
            uistack(speedLineHandles, 'top');
            if ~isempty(speedAvgHandle) && all(ishandle(speedAvgHandle))
                uistack(speedAvgHandle, 'top');
            end
        end
        yline(speedAx, p.Results.immobileSpeedThreshold, '--', ...
            sprintf('Immobile threshold (%.1f mm/s)', p.Results.immobileSpeedThreshold), ...
            'Color', [0.35 0.35 0.35], 'LineWidth', 1.0, ...
            'LabelHorizontalAlignment', 'left', 'LabelVerticalAlignment', 'bottom');
        ylabel(speedAx, 'Speed (mm/s)', 'FontSize', 12, 'FontWeight', 'bold');
        xlabel(speedAx, xLabelStr, 'FontSize', 12, 'FontWeight', 'bold');
        title(speedAx, sprintf('Instantaneous speed (window = %.3g s, immobile >= %.2g s)', ...
            p.Results.speedWindowSec, p.Results.immobileMinDurationSec), ...
            'FontSize', 11, 'FontWeight', 'normal');
        linkaxes([ax, speedAx], 'x');
    end

    if ~isempty(strtrim(char(string(p.Results.savePath))))
        exportgraphics(fig, char(string(p.Results.savePath)));
    end

    R = struct();
    R.figure = fig;
    R.axes = ax;
    R.lineHandles = hLines;
    R.speedAxes = speedAx;
    R.speedLineHandles = speedLineHandles;
    R.speedAverageHandle = speedAvgHandle;
    R.avgSpeed = avgSpeed;
    R.immobileMask = immobileMask;
    R.immobilePatchHandles = immobilePatchHandles;
    R.immobileSpeedPatchHandles = immobileSpeedPatchHandles;
    R.extracted = extracted;
    R.dimensionIndex = dimIdx;
    R.dimensionLabel = dimLabel;
    R.markerLabelsPlotted = labels;
end

function hPatches = localShadeBooleanSpans(ax, x, mask, shadeColor, shadeAlpha)
    hPatches = gobjects(0);
    if isempty(mask) || ~any(mask)
        return;
    end

    mask = logical(mask(:));
    x = x(:);
    if numel(mask) ~= numel(x)
        error('plotPosterMarkerTimeSeries:ShadeMaskLengthMismatch', ...
            'Immobility mask length must match x-axis length.');
    end

    % Find contiguous true runs.
    d = diff([false; mask; false]);
    runStarts = find(d == 1);
    runEnds = find(d == -1) - 1;

    yL = ylim(ax);
    hold(ax, 'on');
    hPatches = gobjects(numel(runStarts), 1);
    for i = 1:numel(runStarts)
        s = runStarts(i);
        e = runEnds(i);
        x0 = x(s);
        x1 = x(e);
        if s > 1
            x0 = 0.5 * (x(s-1) + x(s));
        end
        if e < numel(x)
            x1 = 0.5 * (x(e) + x(e+1));
        end
        hPatches(i) = patch(ax, [x0 x1 x1 x0], [yL(1) yL(1) yL(2) yL(2)], shadeColor, ...
            'FaceAlpha', shadeAlpha, 'EdgeColor', 'none', 'HandleVisibility', 'off');
    end
    uistack(hPatches, 'bottom');
end

function dimIdx = localResolveDimension(dimIn)
    if isnumeric(dimIn) && isscalar(dimIn) && any(dimIn == [1 2 3])
        dimIdx = double(dimIn);
        return;
    end
    dimStr = lower(strtrim(char(string(dimIn))));
    switch dimStr
        case 'x'
            dimIdx = 1;
        case 'y'
            dimIdx = 2;
        case 'z'
            dimIdx = 3;
        otherwise
            error('plotPosterMarkerTimeSeries:BadDimension', ...
                'dimension must be ''x'', ''y'', ''z'', or 1/2/3.');
    end
end

function x = localBuildX(extracted, timeUnits, normalizeToZero)
    timeUnits = lower(strtrim(char(string(timeUnits))));
    switch timeUnits
        case {'seconds', 'sec', 's'}
            x = extracted.timeSec;
        case {'frames', 'frame'}
            x = extracted.frameRange;
        otherwise
            error('plotPosterMarkerTimeSeries:BadTimeUnits', ...
                'timeUnits must be ''seconds'' or ''frames''.');
    end

    if normalizeToZero
        x = x - x(1);
    end
end

function colors = localResolveColors(nLines, userColors)
    if isempty(userColors)
        colors = localPosterGradientColors(nLines);
        return;
    end

    if size(userColors, 2) ~= 3
        error('plotPosterMarkerTimeSeries:BadColors', ...
            'colors must be an n x 3 RGB matrix.');
    end

    if size(userColors, 1) == 1 && nLines > 1
        colors = repmat(userColors, nLines, 1);
    elseif size(userColors, 1) == nLines
        colors = userColors;
    else
        error('plotPosterMarkerTimeSeries:BadColorsCount', ...
            'colors must have either 1 row or %d rows.', nLines);
    end
end

function colors = localPosterGradientColors(nLines)
    if nLines <= 0
        colors = zeros(0, 3);
        return;
    end

    % Smooth sequential palette for poster overlays (less categorical than lines()).
    nBase = max(64, nLines);
    cmap = parula(nBase);
    idx = round(linspace(8, nBase - 6, nLines)); % avoid extreme endpoints
    colors = cmap(idx, :);
end

function localApplyPosterAxesStyle(ax, gridOnFlag)
    set(ax, ...
        'FontSize', 11, ...
        'LineWidth', 1.0, ...
        'Box', 'off', ...
        'Color', 'none', ...
        'TickDir', 'out');

    if gridOnFlag
        grid(ax, 'on');
        ax.GridAlpha = 0.18;
        ax.MinorGridAlpha = 0.10;
        try
            ax.XMinorGrid = 'off';
            ax.YMinorGrid = 'off';
        catch
        end
    else
        grid(ax, 'off');
    end
end
