% Make onset-aligned grant figures for revised unitary and compound LAR bouts.
%
% This script uses the revised valley-delimited bout tables generated by
% run_grant_event_shape_interval_visualization.m. For shape averaging, t = 0
% is not the dominant peak. It is the beginning of the bout excursion,
% estimated as the last low-threshold crossing before the first same-bout
% subpeak. This makes compound duration visible in the average waveform.

clear;
close all;
clc;

set(0, 'DefaultFigureVisible', 'off');

scriptPath = mfilename('fullpath');
repoRoot = fileparts(fileparts(scriptPath));
scratchRoot = fullfile(repoRoot, 'scratch', 'unitary_event_validation_20260508');
outputRoot = fullfile(scratchRoot, 'outputs');
tableRoot = fullfile(scratchRoot, 'tables');
workspacePath = fullfile(scratchRoot, 'grant_revised_bout_shape_workspace.mat');
if ~isfolder(outputRoot)
    mkdir(outputRoot);
end
if ~isfolder(tableRoot)
    mkdir(tableRoot);
end

addpath(fullfile(repoRoot, 'CODE', 'ACCELEROMETER'));
addpath(fullfile(repoRoot, 'CODE', 'ANALYSIS'));

magnitudeRoot = LF_resolveFolder({ ...
    '/Users/yoe/Documents/DATA/Waseda-ACC/MATLAB-CONVERTED/MAGNITUDES', ...
    '/Users/yoe/Dropbox/WORK/Data/Waseda-ACC/MAGNITUDES', ...
    '/Users/yoe/Library/CloudStorage/Dropbox/WORK/Data/Waseda-ACC/MAGNITUDES'});

loadedData = load(workspacePath, 'settings', 'boutTable', 'subpeakTable', 'intervalTable');
settings = loadedData.settings;
boutTable = loadedData.boutTable;
subpeakTable = loadedData.subpeakTable;
intervalTable = loadedData.intervalTable;

plotWindowSeconds = [-0.25 4.25];
contextCache = containers.Map('KeyType', 'char', 'ValueType', 'any');

onsetRows = struct([]);
eventSignalSnippets = [];
envelopeSnippets = [];
snippetMetadata = struct([]);
relativeTimeSec = [];

fprintf('Building onset-aligned snippets from %d revised bouts.\n', height(boutTable));

for boutIndex = 1:height(boutTable)
    row = boutTable(boutIndex, :);
    fileName = char(row.fileName);
    fileContext = LF_getCachedContext(fileName, contextCache, magnitudeRoot, settings);

    if isempty(relativeTimeSec)
        relativeSamples = round(plotWindowSeconds(1) .* fileContext.samplingFrequency): ...
            round(plotWindowSeconds(2) .* fileContext.samplingFrequency);
        relativeTimeSec = relativeSamples(:) ./ fileContext.samplingFrequency;
    end

    subRows = subpeakTable(string(subpeakTable.fileName) == string(row.fileName) & ...
        subpeakTable.dominantPeakIndex == row.dominantPeakIndex, :);
    subpeakIndices = sort(subRows.subpeakIndex(:));
    if isempty(subpeakIndices)
        continue;
    end

    onsetIndex = LF_estimateBoutOnsetIndex(fileContext, subpeakIndices(1), settings);
    eventSignalSnippet = LF_extractSnippet(fileContext.eventSignal, onsetIndex, relativeSamples);
    envelopeSnippet = LF_extractSnippet(fileContext.motionEnvelope, onsetIndex, relativeSamples);
    if any(~isfinite(eventSignalSnippet)) || any(~isfinite(envelopeSnippet))
        continue;
    end

    snippetIndex = size(eventSignalSnippets, 2) + 1;
    eventSignalSnippets(:, snippetIndex) = eventSignalSnippet(:); %#ok<SAGROW>
    envelopeSnippets(:, snippetIndex) = envelopeSnippet(:); %#ok<SAGROW>

    subpeakTimesFromOnset = (subpeakIndices - onsetIndex) ./ fileContext.samplingFrequency;
    dominantTimeFromOnset = (row.dominantPeakIndex - onsetIndex) ./ fileContext.samplingFrequency;

    onsetRows(end + 1, 1).fileName = row.fileName; %#ok<AGROW>
    onsetRows(end, 1).subjectID = row.subjectID;
    onsetRows(end, 1).condition = row.condition;
    onsetRows(end, 1).dominantPeakIndex = row.dominantPeakIndex;
    onsetRows(end, 1).onsetIndex = onsetIndex;
    onsetRows(end, 1).onsetTimeSec = fileContext.timeSec(onsetIndex);
    onsetRows(end, 1).dominantTimeFromOnsetSec = dominantTimeFromOnset;
    onsetRows(end, 1).nSubpeaks = row.nSubpeaks;
    onsetRows(end, 1).isUnitaryBout = row.isUnitaryBout;
    onsetRows(end, 1).isCompoundBout = row.isCompoundBout;
    onsetRows(end, 1).activeSubpeakSpanSec = row.activeSubpeakSpanSec;
    onsetRows(end, 1).subpeakTimesFromOnsetText = ...
        string(strjoin(cellstr(string(round(subpeakTimesFromOnset(:).', 4))), ';'));
    onsetRows(end, 1).snippetIndex = snippetIndex;

    snippetMetadata(end + 1, 1).fileName = row.fileName; %#ok<AGROW>
    snippetMetadata(end, 1).condition = row.condition;
    snippetMetadata(end, 1).nSubpeaks = row.nSubpeaks;
    snippetMetadata(end, 1).isCompoundBout = row.isCompoundBout;
end

onsetBoutTable = struct2table(onsetRows);
snippetMetadataTable = struct2table(snippetMetadata);
writetable(onsetBoutTable, fullfile(tableRoot, 'grant_onset_aligned_bouts.csv'));

LF_makeOnsetSummaryFigure(relativeTimeSec, eventSignalSnippets, envelopeSnippets, ...
    snippetMetadataTable, onsetBoutTable, intervalTable, outputRoot);

selectedFileName = LF_chooseSingleTrial(onsetBoutTable, magnitudeRoot);
fileContext = LF_getCachedContext(selectedFileName, contextCache, magnitudeRoot, settings);
LF_makeSingleTrialTraceFigure(fileContext, onsetBoutTable, subpeakTable, selectedFileName, outputRoot);
LF_makePeakOnlyExampleTraceFigure(fileContext, onsetBoutTable, subpeakTable, selectedFileName, outputRoot);
LF_makeLongScaleExampleTraceFigure(fileContext, onsetBoutTable, subpeakTable, selectedFileName, outputRoot);
fixedWindowFigure = plotEnvelopeEventsWithNoiseBand(fullfile(magnitudeRoot, selectedFileName), ...
    'WindowSeconds', [1500 2500], ...
    'BaselineWindowSeconds', settings.baselineWindowSeconds, ...
    'NoiseWindowSeconds', settings.noiseWindowSeconds, ...
    'ThresholdSigma', settings.thresholdSigma, ...
    'CompoundSearchWindowSeconds', settings.lobeSearchWindowSeconds, ...
    'CompoundSubpeakThresholdSigma', settings.lowThresholdSigma, ...
    'CompoundSubpeakMinDistanceSeconds', settings.subpeakMinDistanceSeconds, ...
    'CompoundValleyFraction', settings.lobeValleyFraction, ...
    'OutputPngPath', fullfile(outputRoot, 'grant_lar_trace_1500_2500s_unitary_compound_peaks.png'), ...
    'OutputFigPath', fullfile(outputRoot, 'grant_lar_trace_1500_2500s_unitary_compound_peaks.fig'), ...
    'FigureTitle', sprintf('Original motion-envelope trace, 1500-2500 s: %s %s', ...
        char(fileContext.subjectID), erase(char(fileContext.condition), '_stand')), ...
    'FigurePosition', [100 100 1500 430]);
close(fixedWindowFigure);

save(fullfile(scratchRoot, 'grant_onset_aligned_workspace.mat'), ...
    'settings', 'plotWindowSeconds', 'relativeTimeSec', 'onsetBoutTable', ...
    'eventSignalSnippets', 'envelopeSnippets', 'snippetMetadataTable', ...
    'selectedFileName', '-v7.3');

fprintf('Saved onset-aligned grant figures. Selected trace trial: %s\n', selectedFileName);

function fileContext = LF_getCachedContext(fileName, contextCache, magnitudeRoot, settings)
if isKey(contextCache, fileName)
    fileContext = contextCache(fileName);
else
    fileContext = LF_buildFileContext(fileName, magnitudeRoot, settings);
    contextCache(fileName) = fileContext;
end
end

function fileContext = LF_buildFileContext(fileName, magnitudeRoot, settings)
magnitudePath = fullfile(magnitudeRoot, fileName);
loadedMagnitude = load(magnitudePath, 'motionData');
motionData = loadedMagnitude.motionData;
samplingFrequency = motionData.meta.sampleRateHz;

existingFigures = findall(0, 'Type', 'figure');
eventOutput = extractEnvelopeEvents(motionData.motionEnvelope, samplingFrequency, ...
    'TimeSec', motionData.timeSec, ...
    'BaselineWindowSeconds', settings.baselineWindowSeconds, ...
    'NoiseWindowSeconds', settings.noiseWindowSeconds, ...
    'RectifyResidual', true, ...
    'ThresholdSigma', settings.thresholdSigma, ...
    'CompoundSearchWindowSeconds', settings.lobeSearchWindowSeconds, ...
    'CompoundSubpeakThresholdSigma', settings.lowThresholdSigma, ...
    'CompoundSubpeakMinDistanceSeconds', settings.subpeakMinDistanceSeconds, ...
    'CompoundValleyFraction', settings.lobeValleyFraction, ...
    'MakeWaveformFigure', false, ...
    'MakeSummaryFigure', false);
newFigures = setdiff(findall(0, 'Type', 'figure'), existingFigures);
close(newFigures);

fileInfo = LF_parseWasedaFileName(fileName);
fileContext = struct();
fileContext.fileName = string(fileName);
fileContext.subjectID = string(fileInfo.subjectID);
fileContext.condition = string(fileInfo.condition);
fileContext.samplingFrequency = samplingFrequency;
fileContext.timeSec = motionData.timeSec(:);
fileContext.motionEnvelope = motionData.motionEnvelope(:);
fileContext.eventSignal = eventOutput.noiseEstimate.eventSignal(:);
fileContext.noiseSigma = eventOutput.noiseEstimate.noiseSigma(:);
fileContext.lowThreshold = settings.lowThresholdSigma .* median(fileContext.noiseSigma, 'omitnan');
fileContext.eventTable = eventOutput.eventTable;
end

function folderPath = LF_resolveFolder(candidateFolders)
for folderIndex = 1:numel(candidateFolders)
    candidateFolder = candidateFolders{folderIndex};
    if isfolder(candidateFolder)
        folderPath = candidateFolder;
        return;
    end
end
error('Could not find any candidate folder:\n%s', strjoin(string(candidateFolders), newline));
end

function fileInfo = LF_parseWasedaFileName(fileName)
tokens = regexp(fileName, '^\d+_(sub\d+)_(.+)_acc1_chest_motionEnvelope\.mat$', 'tokens', 'once');
if isempty(tokens)
    error('Could not parse file name: %s', fileName);
end
fileInfo = struct();
fileInfo.subjectID = string(tokens{1});
fileInfo.condition = string(tokens{2});
end

function onsetIndex = LF_estimateBoutOnsetIndex(fileContext, firstSubpeakIndex, settings)
samplingFrequency = fileContext.samplingFrequency;
eventSignal = fileContext.eventSignal;
lowThreshold = fileContext.lowThreshold;
lookbackSamples = max(1, round(1.25 .* samplingFrequency));
searchStart = max(1, firstSubpeakIndex - lookbackSamples);
searchValues = eventSignal(searchStart:firstSubpeakIndex);
belowThresholdPositions = find(searchValues <= lowThreshold);

if ~isempty(belowThresholdPositions)
    onsetIndex = searchStart + belowThresholdPositions(end) - 1;
else
    [~, minimumPosition] = min(searchValues);
    onsetIndex = searchStart + minimumPosition - 1;
end

% Move to the first sample after the quiet point that starts the excursion.
while onsetIndex < firstSubpeakIndex && eventSignal(onsetIndex) <= lowThreshold
    onsetIndex = onsetIndex + 1;
end
onsetIndex = max(1, onsetIndex - 1);
end

function snippet = LF_extractSnippet(signal, centerIndex, relativeSamples)
sampleIndices = centerIndex + relativeSamples(:);
if any(sampleIndices < 1) || any(sampleIndices > numel(signal))
    snippet = NaN(numel(relativeSamples), 1);
else
    snippet = signal(sampleIndices);
end
end

function normalizedMatrix = LF_normalizeColumns(matrix)
normalizedMatrix = matrix;
for columnIndex = 1:size(matrix, 2)
    values = matrix(:, columnIndex);
    baseline = median(values(1:min(20, numel(values))), 'omitnan');
    values = values - baseline;
    scaleValue = max(abs(values), [], 'omitnan');
    if isfinite(scaleValue) && scaleValue > 0
        values = values ./ scaleValue;
    end
    normalizedMatrix(:, columnIndex) = values;
end
end

function [medianTrace, lowTrace, highTrace] = LF_traceSummary(matrix)
medianTrace = median(matrix, 2, 'omitnan');
lowTrace = prctile(matrix, 25, 2);
highTrace = prctile(matrix, 75, 2);
end

function LF_plotShadedTrace(ax, xValues, medianTrace, lowTrace, highTrace, colorValue, displayName)
patch(ax, [xValues(:); flipud(xValues(:))], [lowTrace(:); flipud(highTrace(:))], ...
    colorValue, 'FaceAlpha', 0.15, 'EdgeColor', 'none', 'HandleVisibility', 'off');
plot(ax, xValues, medianTrace, 'Color', colorValue, 'LineWidth', 2.5, 'DisplayName', displayName);
end

function LF_makeOnsetSummaryFigure(relativeTimeSec, eventSignalSnippets, envelopeSnippets, ...
    snippetMetadataTable, onsetBoutTable, intervalTable, outputRoot)
unitaryMask = ~snippetMetadataTable.isCompoundBout;
compoundMask = snippetMetadataTable.isCompoundBout;

envelopeNormalized = LF_normalizeColumns(envelopeSnippets);

[unitEnvelopeMedian, unitEnvelopeLow, unitEnvelopeHigh] = LF_traceSummary(envelopeNormalized(:, unitaryMask));
[compoundEnvelopeMedian, compoundEnvelopeLow, compoundEnvelopeHigh] = LF_traceSummary(envelopeNormalized(:, compoundMask));

secondaryTimesFromFirstPeak = LF_collectSecondaryTimesFromFirstPeak(onsetBoutTable);
withinCompoundIntervalValues = intervalTable.intervalSec;
interCompoundIntervalsSec = LF_collectInterCompoundFirstPeakIntervals(onsetBoutTable);
interCompoundIntervalsForPlot = interCompoundIntervalsSec(interCompoundIntervalsSec <= 20);

figureHandle = figure('Color', 'w', 'Position', [80 70 1500 980]);
t = tiledlayout(3, 3, 'TileSpacing', 'compact', 'Padding', 'compact');
title(t, 'Onset-aligned unitary and compound LAR event structure', ...
    'FontSize', 18, 'FontWeight', 'bold');
subtitle(t, 't = 0 is the estimated bout onset: the low-threshold crossing before the first same-bout subpeak.', ...
    'FontSize', 11);

ax = nexttile(t, 1);
hold(ax, 'on');
LF_plotShadedTrace(ax, relativeTimeSec, unitEnvelopeMedian, unitEnvelopeLow, unitEnvelopeHigh, [0.05 0.35 0.70], 'unitary');
LF_plotShadedTrace(ax, relativeTimeSec, compoundEnvelopeMedian, compoundEnvelopeLow, compoundEnvelopeHigh, [0.80 0.30 0.10], 'compound');
xline(ax, 0, '--k', 'HandleVisibility', 'off');
grid(ax, 'on');
xlabel(ax, 'time from estimated bout onset (s)');
ylabel(ax, 'normalized motion envelope');
title(ax, 'Original motion-envelope shape', 'FontWeight', 'normal');
legend(ax, 'Location', 'northeast', 'Box', 'off');

ax = nexttile(t, 2);
compoundSnippetIndices = find(compoundMask);
firstPeakLatencies = LF_getFirstPeakLatencies(onsetBoutTable, compoundSnippetIndices);
[~, sortOrder] = sort(firstPeakLatencies, 'ascend');
firstPeakSortedCompoundIndices = compoundSnippetIndices(sortOrder);
imagesc(ax, relativeTimeSec, 1:numel(firstPeakSortedCompoundIndices), ...
    envelopeNormalized(:, firstPeakSortedCompoundIndices).');
colormap(ax, hot);
colorbar(ax);
xline(ax, 0, '--w', 'LineWidth', 1.2);
hold(ax, 'on');
LF_overlayCompoundRasterPeaks(ax, onsetBoutTable, firstPeakSortedCompoundIndices);
grid(ax, 'off');
xlabel(ax, 'time from estimated bout onset (s)');
ylabel(ax, 'compound bouts');
title(ax, 'Compound raster, sorted by first peak', 'FontWeight', 'normal');

ax = nexttile(t, 3);
boxchart(ax, categorical(onsetBoutTable.isCompoundBout, [false true], {'unitary', 'compound'}), ...
    onsetBoutTable.dominantTimeFromOnsetSec);
grid(ax, 'on');
ylabel(ax, 'time from onset to dominant peak (s)');
title(ax, 'Peak latency after onset', 'FontWeight', 'normal');

ax = nexttile(t, 4);
[~, sortOrder] = sort(onsetBoutTable.activeSubpeakSpanSec(compoundSnippetIndices), 'ascend');
compoundSnippetIndices = compoundSnippetIndices(sortOrder);
imagesc(ax, relativeTimeSec, 1:numel(compoundSnippetIndices), ...
    envelopeNormalized(:, compoundSnippetIndices).');
colormap(ax, hot);
colorbar(ax);
xline(ax, 0, '--w', 'LineWidth', 1.2);
hold(ax, 'on');
LF_overlayCompoundRasterPeaks(ax, onsetBoutTable, compoundSnippetIndices);
grid(ax, 'off');
xlabel(ax, 'time from estimated bout onset (s)');
ylabel(ax, 'compound bouts');
title(ax, 'Compound-bout raster, sorted by duration', 'FontWeight', 'normal');

ax = nexttile(t, 5);
histogram(ax, secondaryTimesFromFirstPeak, 'BinEdges', 0:0.05:3.5, ...
    'FaceColor', [0.80 0.30 0.10], 'EdgeColor', 'none');
grid(ax, 'on');
xlabel(ax, 'secondary subpeak time from first peak (s)');
ylabel(ax, 'subpeak count');
title(ax, 'Secondary element timing', 'FontWeight', 'normal');

ax = nexttile(t, 6);
withinCompoundIntervalValuesForPlot = withinCompoundIntervalValues(withinCompoundIntervalValues <= 1.5);
histogram(ax, withinCompoundIntervalValuesForPlot, 'BinEdges', 0:0.05:1.5, ...
    'FaceColor', [0.20 0.45 0.75], 'EdgeColor', 'none');
grid(ax, 'on');
xlabel(ax, 'adjacent inter-subpeak interval (s)');
ylabel(ax, 'interval count');
title(ax, 'Within-compound element spacing', 'FontWeight', 'normal');
xlim(ax, [0 1.5]);

ax = nexttile(t, 7);
boutCategories = categorical({'unitary', 'compound'}, {'unitary', 'compound'}, 'Ordinal', true);
bar(ax, boutCategories, [sum(unitaryMask), sum(compoundMask)], ...
    'FaceColor', [0.45 0.55 0.65]);
grid(ax, 'on');
ylabel(ax, 'bout count');
title(ax, 'Bout classes', 'FontWeight', 'normal');

ax = nexttile(t, 8);
histogram(ax, onsetBoutTable.nSubpeaks(onsetBoutTable.isCompoundBout), ...
    'BinEdges', 1.5:1:(max(onsetBoutTable.nSubpeaks) + 0.5), ...
    'FaceColor', [0.80 0.30 0.10], 'EdgeColor', 'w');
grid(ax, 'on');
xlabel(ax, 'subpeaks per compound bout');
ylabel(ax, 'bout count');
title(ax, 'Compound-bout complexity', 'FontWeight', 'normal');

ax = nexttile(t, 9);
histogram(ax, interCompoundIntervalsForPlot, 'BinEdges', 0:0.5:20, ...
    'FaceColor', [0.55 0.45 0.72], 'EdgeColor', 'none');
grid(ax, 'on');
xlabel(ax, 'interval between compound first peaks (s)');
ylabel(ax, 'interval count');
title(ax, 'Inter-compound-event intervals <= 20 s', 'FontWeight', 'normal');
xlim(ax, [0 20]);

exportgraphics(figureHandle, fullfile(outputRoot, 'grant_onset_aligned_unitary_vs_compound_event_shapes.png'), ...
    'Resolution', 220);
savefig(figureHandle, fullfile(outputRoot, 'grant_onset_aligned_unitary_vs_compound_event_shapes.fig'));
close(figureHandle);
end

function LF_overlayCompoundRasterPeaks(ax, onsetBoutTable, compoundSnippetIndices)
for rasterRow = 1:numel(compoundSnippetIndices)
    boutIndex = compoundSnippetIndices(rasterRow);
    subpeakTimes = LF_parseNumberList(onsetBoutTable.subpeakTimesFromOnsetText(boutIndex));
    if isempty(subpeakTimes)
        continue;
    end
    plot(ax, subpeakTimes, repmat(rasterRow, size(subpeakTimes)), '.', ...
        'Color', [0.20 0.75 1.00], 'MarkerSize', 7, 'HandleVisibility', 'off');
end
end

function firstPeakLatencies = LF_getFirstPeakLatencies(onsetBoutTable, compoundSnippetIndices)
firstPeakLatencies = NaN(numel(compoundSnippetIndices), 1);
for rowIndex = 1:numel(compoundSnippetIndices)
    boutIndex = compoundSnippetIndices(rowIndex);
    subpeakTimes = LF_parseNumberList(onsetBoutTable.subpeakTimesFromOnsetText(boutIndex));
    if isempty(subpeakTimes)
        continue;
    end
    firstPeakLatencies(rowIndex) = min(subpeakTimes);
end
end

function secondaryTimes = LF_collectSecondaryTimesFromFirstPeak(onsetBoutTable)
secondaryTimes = [];
for rowIndex = 1:height(onsetBoutTable)
    if ~onsetBoutTable.isCompoundBout(rowIndex)
        continue;
    end
    values = LF_parseNumberList(onsetBoutTable.subpeakTimesFromOnsetText(rowIndex));
    if numel(values) > 1
        secondaryTimes = [secondaryTimes; (values(2:end) - values(1)).']; %#ok<AGROW>
    end
end
end

function intervalsSec = LF_collectInterCompoundFirstPeakIntervals(onsetBoutTable)
intervalsSec = [];
fileNames = unique(onsetBoutTable.fileName);
for fileIndex = 1:numel(fileNames)
    fileMask = string(onsetBoutTable.fileName) == string(fileNames(fileIndex));
    compoundRows = onsetBoutTable(fileMask & onsetBoutTable.isCompoundBout, :);
    if height(compoundRows) < 2
        continue;
    end
    firstPeakTimesSec = NaN(height(compoundRows), 1);
    for rowIndex = 1:height(compoundRows)
        subpeakTimesFromOnset = LF_parseNumberList(compoundRows.subpeakTimesFromOnsetText(rowIndex));
        firstPeakTimesSec(rowIndex) = compoundRows.onsetTimeSec(rowIndex) + min(subpeakTimesFromOnset);
    end
    firstPeakTimesSec = sort(firstPeakTimesSec(isfinite(firstPeakTimesSec)));
    intervalsSec = [intervalsSec; diff(firstPeakTimesSec)]; %#ok<AGROW>
end
end

function values = LF_parseNumberList(textValue)
if strlength(textValue) == 0
    values = [];
else
    values = str2double(split(string(textValue), ';')).';
end
end

function selectedFileName = LF_chooseSingleTrial(onsetBoutTable, magnitudeRoot)
summaryTable = groupsummary(onsetBoutTable, 'fileName', {'sum'}, {'isUnitaryBout', 'isCompoundBout'});
summaryTable.balanceScore = min(summaryTable.sum_isUnitaryBout, summaryTable.sum_isCompoundBout);
summaryTable.totalScore = summaryTable.sum_isUnitaryBout + summaryTable.sum_isCompoundBout;
summaryTable.p99AfterSettling = NaN(height(summaryTable), 1);

for rowIndex = 1:height(summaryTable)
    fileName = char(summaryTable.fileName(rowIndex));
    loadedData = load(fullfile(magnitudeRoot, fileName), 'motionData');
    timeSec = loadedData.motionData.timeSec(:);
    motionEnvelope = loadedData.motionData.motionEnvelope(:);
    settledMask = timeSec >= 300;
    summaryTable.p99AfterSettling(rowIndex) = prctile(motionEnvelope(settledMask), 99);
end

quietEnough = summaryTable.p99AfterSettling <= 0.04 & ...
    summaryTable.totalScore >= 40 & summaryTable.balanceScore >= 5;
if any(quietEnough)
    candidateTable = summaryTable(quietEnough, :);
else
    candidateTable = summaryTable;
end

candidateTable.selectionScore = candidateTable.balanceScore .* 20 + ...
    candidateTable.totalScore .* 0.1 - candidateTable.p99AfterSettling .* 1000;
candidateTable = sortrows(candidateTable, 'selectionScore', 'descend');
selectedFileName = char(candidateTable.fileName(1));
end

function LF_makeSingleTrialTraceFigure(fileContext, onsetBoutTable, subpeakTable, selectedFileName, outputRoot)
trialBouts = onsetBoutTable(string(onsetBoutTable.fileName) == string(selectedFileName), :);
trialBouts = sortrows(trialBouts, 'onsetTimeSec');

figureHandle = figure('Color', 'w', 'Position', [80 90 1550 820]);
t = tiledlayout(2, 1, 'TileSpacing', 'compact', 'Padding', 'compact');
title(t, sprintf('One trial with unitary and compound events: %s %s', ...
    char(fileContext.subjectID), erase(char(fileContext.condition), '_stand')), ...
    'Interpreter', 'none', 'FontSize', 16, 'FontWeight', 'bold');
subtitle(t, sprintf('Motion envelope is the analyzed magnitude signal; file: %s', selectedFileName), ...
    'Interpreter', 'none', 'FontSize', 11);

ax = nexttile(t, 1);
hold(ax, 'on');
plot(ax, fileContext.timeSec ./ 60, fileContext.motionEnvelope, ...
    'Color', [0.08 0.20 0.38], 'LineWidth', 0.8, 'DisplayName', 'motion envelope');
LF_addBoutMarkers(ax, fileContext, trialBouts, subpeakTable, true, 0, false);
grid(ax, 'on');
xlabel(ax, 'time (min)');
ylabel(ax, 'motion envelope');
title(ax, 'Full trial overview: onset markers only', 'FontWeight', 'normal');
legend(ax, 'Location', 'northoutside', 'Orientation', 'horizontal', 'Box', 'off');

bestWindow = LF_chooseDetailedWindow(trialBouts);
windowPaddingSec = 2;
windowStartSec = max(min(bestWindow.onsetTimeSec) - windowPaddingSec, min(fileContext.timeSec));
windowEndSec = min(max(bestWindow.onsetTimeSec) + windowPaddingSec, max(fileContext.timeSec));
windowMask = fileContext.timeSec >= windowStartSec & fileContext.timeSec <= windowEndSec;

ax = nexttile(t, 2);
hold(ax, 'on');
plot(ax, fileContext.timeSec(windowMask) - windowStartSec, fileContext.motionEnvelope(windowMask), ...
    'Color', [0.08 0.20 0.38], 'LineWidth', 1.3, 'DisplayName', 'motion envelope');
LF_addBoutMarkers(ax, fileContext, bestWindow, subpeakTable, false, windowStartSec, true);
grid(ax, 'on');
xlabel(ax, 'time within zoom window (s)');
ylabel(ax, 'motion envelope');
title(ax, 'Zoomed segment: unitary events and compound bouts in the same trial', 'FontWeight', 'normal');
legend(ax, 'Location', 'northoutside', 'Orientation', 'horizontal', 'Box', 'off');

exportgraphics(figureHandle, fullfile(outputRoot, 'grant_single_trial_unitary_compound_magnitude_trace.png'), ...
    'Resolution', 220);
savefig(figureHandle, fullfile(outputRoot, 'grant_single_trial_unitary_compound_magnitude_trace.fig'));
close(figureHandle);
end

function LF_makePeakOnlyExampleTraceFigure(fileContext, onsetBoutTable, subpeakTable, selectedFileName, outputRoot)
trialBouts = onsetBoutTable(string(onsetBoutTable.fileName) == string(selectedFileName), :);
trialBouts = sortrows(trialBouts, 'onsetTimeSec');
[exampleWindow, windowStartSec, windowEndSec] = LF_choosePeakOnlyWindow(fileContext, trialBouts);

windowMask = fileContext.timeSec >= windowStartSec & fileContext.timeSec <= windowEndSec;

figureHandle = figure('Color', 'w', 'Position', [100 120 1350 520]);
ax = axes(figureHandle);
hold(ax, 'on');
plot(ax, fileContext.timeSec(windowMask) - windowStartSec, fileContext.motionEnvelope(windowMask), ...
    'Color', [0.06 0.18 0.34], 'LineWidth', 1.6, 'DisplayName', 'motion envelope');

unitaryColor = [0.05 0.35 0.70];
compoundColor = [0.80 0.30 0.10];
LF_addPeakMarkers(ax, fileContext, exampleWindow(exampleWindow.isUnitaryBout, :), ...
    subpeakTable, windowStartSec, unitaryColor, 'unitary peak');
LF_addPeakMarkers(ax, fileContext, exampleWindow(exampleWindow.isCompoundBout, :), ...
    subpeakTable, windowStartSec, compoundColor, 'compound subpeaks');

grid(ax, 'on');
xlabel(ax, 'time within zoom window (s)');
ylabel(ax, 'motion envelope');
title(ax, sprintf('Example LAR envelope segment with unitary and compound peaks: %s %s', ...
    char(fileContext.subjectID), erase(char(fileContext.condition), '_stand')), ...
    'Interpreter', 'none', 'FontWeight', 'bold');
subtitle(ax, sprintf('File: %s', selectedFileName), 'Interpreter', 'none');
legend(ax, 'Location', 'northoutside', 'Orientation', 'horizontal', 'Box', 'off');

exportgraphics(figureHandle, fullfile(outputRoot, 'grant_example_envelope_trace_unitary_compound_peaks.png'), ...
    'Resolution', 240);
savefig(figureHandle, fullfile(outputRoot, 'grant_example_envelope_trace_unitary_compound_peaks.fig'));
close(figureHandle);
end

function LF_makeLongScaleExampleTraceFigure(fileContext, onsetBoutTable, subpeakTable, selectedFileName, outputRoot)
trialBouts = onsetBoutTable(string(onsetBoutTable.fileName) == string(selectedFileName), :);
trialBouts = sortrows(trialBouts, 'onsetTimeSec');
[windowStartSec, windowEndSec] = LF_chooseLongScaleWindow(fileContext, trialBouts);
windowMask = fileContext.timeSec >= windowStartSec & fileContext.timeSec <= windowEndSec;
windowBouts = trialBouts(trialBouts.onsetTimeSec >= windowStartSec & ...
    trialBouts.onsetTimeSec <= windowEndSec, :);

figureHandle = figure('Color', 'w', 'Position', [80 180 1500 430]);
ax = axes(figureHandle);
hold(ax, 'on');
plot(ax, fileContext.timeSec(windowMask) - windowStartSec, fileContext.motionEnvelope(windowMask), ...
    'Color', [0.02 0.02 0.02], 'LineWidth', 0.85, 'DisplayName', 'motion envelope');

windowMax = prctile(fileContext.motionEnvelope(windowMask), 99.8);
if ~isfinite(windowMax) || windowMax <= 0
    windowMax = max(fileContext.motionEnvelope(windowMask), [], 'omitnan');
end
yLimitTop = max(0.055, min(0.15, windowMax .* 1.25));
ylim(ax, [0 yLimitTop]);

markerOffset = 0.035 .* yLimitTop;
LF_addAbovePeakMarkers(ax, fileContext, windowBouts(windowBouts.isUnitaryBout, :), ...
    subpeakTable, windowStartSec, markerOffset, yLimitTop, [0.05 0.35 0.70], 'unitary peak');
LF_addAbovePeakMarkers(ax, fileContext, windowBouts(windowBouts.isCompoundBout, :), ...
    subpeakTable, windowStartSec, markerOffset, yLimitTop, [0.80 0.30 0.10], 'compound subpeaks');

grid(ax, 'on');
xlabel(ax, 'time within LAR segment (s)');
ylabel(ax, 'motion envelope');
title(ax, sprintf('Original motion-envelope trace with unitary and compound peaks: %s %s', ...
    char(fileContext.subjectID), erase(char(fileContext.condition), '_stand')), ...
    'Interpreter', 'none', 'FontWeight', 'normal');
legend(ax, 'Location', 'northoutside', 'Orientation', 'horizontal', 'Box', 'off');

exportgraphics(figureHandle, fullfile(outputRoot, 'grant_long_lar_trace_unitary_compound_peaks.png'), ...
    'Resolution', 240);
savefig(figureHandle, fullfile(outputRoot, 'grant_long_lar_trace_unitary_compound_peaks.fig'));
close(figureHandle);

fprintf('Long-scale example window: %.1f to %.1f s in %s.\n', ...
    windowStartSec, windowEndSec, selectedFileName);
end

function LF_makeFixedWindowExampleTraceFigure(fileContext, onsetBoutTable, subpeakTable, ...
    selectedFileName, outputRoot, windowStartSec, windowEndSec)
trialBouts = onsetBoutTable(string(onsetBoutTable.fileName) == string(selectedFileName), :);
trialBouts = sortrows(trialBouts, 'onsetTimeSec');
windowStartSec = max(windowStartSec, min(fileContext.timeSec));
windowEndSec = min(windowEndSec, max(fileContext.timeSec));
windowMask = fileContext.timeSec >= windowStartSec & fileContext.timeSec <= windowEndSec;
windowBouts = trialBouts(trialBouts.onsetTimeSec >= windowStartSec & ...
    trialBouts.onsetTimeSec <= windowEndSec, :);

figureHandle = figure('Color', 'w', 'Position', [80 180 1500 430]);
ax = axes(figureHandle);
hold(ax, 'on');
plot(ax, fileContext.timeSec(windowMask) - windowStartSec, fileContext.motionEnvelope(windowMask), ...
    'Color', [0.02 0.02 0.02], 'LineWidth', 0.85, 'DisplayName', 'motion envelope');

windowMax = prctile(fileContext.motionEnvelope(windowMask), 99.8);
if ~isfinite(windowMax) || windowMax <= 0
    windowMax = max(fileContext.motionEnvelope(windowMask), [], 'omitnan');
end
yLimitTop = max(0.055, min(0.15, windowMax .* 1.25));
ylim(ax, [0 yLimitTop]);

markerOffset = 0.035 .* yLimitTop;
LF_addAbovePeakMarkers(ax, fileContext, windowBouts(windowBouts.isUnitaryBout, :), ...
    subpeakTable, windowStartSec, markerOffset, yLimitTop, [0.05 0.35 0.70], 'unitary peak');
LF_addAbovePeakMarkers(ax, fileContext, windowBouts(windowBouts.isCompoundBout, :), ...
    subpeakTable, windowStartSec, markerOffset, yLimitTop, [0.80 0.30 0.10], 'compound subpeaks');

grid(ax, 'on');
xlabel(ax, sprintf('time within %.0f-%.0f s segment (s)', windowStartSec, windowEndSec));
ylabel(ax, 'motion envelope');
title(ax, sprintf('Original motion-envelope trace, %.0f-%.0f s: %s %s', ...
    windowStartSec, windowEndSec, char(fileContext.subjectID), erase(char(fileContext.condition), '_stand')), ...
    'Interpreter', 'none', 'FontWeight', 'normal');
legend(ax, 'Location', 'northoutside', 'Orientation', 'horizontal', 'Box', 'off');

exportgraphics(figureHandle, fullfile(outputRoot, 'grant_lar_trace_1500_2500s_unitary_compound_peaks.png'), ...
    'Resolution', 240);
savefig(figureHandle, fullfile(outputRoot, 'grant_lar_trace_1500_2500s_unitary_compound_peaks.fig'));
close(figureHandle);
end

function [windowStartSec, windowEndSec] = LF_chooseLongScaleWindow(fileContext, trialBouts)
settlingEndSec = 300;
windowLengthSec = 3600;
stepSec = 60;
latestStartSec = max(fileContext.timeSec) - windowLengthSec;
if latestStartSec <= settlingEndSec
    windowStartSec = min(max(settlingEndSec, min(fileContext.timeSec)), max(fileContext.timeSec));
    windowEndSec = max(fileContext.timeSec);
    return;
end

startTimes = settlingEndSec:stepSec:latestStartSec;
bestScore = -Inf;
windowStartSec = startTimes(1);
windowEndSec = windowStartSec + windowLengthSec;
for startIndex = 1:numel(startTimes)
    candidateStartSec = startTimes(startIndex);
    candidateEndSec = candidateStartSec + windowLengthSec;
    boutMask = trialBouts.onsetTimeSec >= candidateStartSec & trialBouts.onsetTimeSec <= candidateEndSec;
    candidateBouts = trialBouts(boutMask, :);
    nUnitary = sum(candidateBouts.isUnitaryBout);
    nCompound = sum(candidateBouts.isCompoundBout);
    if nUnitary < 5 || nCompound < 5
        continue;
    end

    signalMask = fileContext.timeSec >= candidateStartSec & fileContext.timeSec <= candidateEndSec;
    p99 = prctile(fileContext.motionEnvelope(signalMask), 99);
    p999 = prctile(fileContext.motionEnvelope(signalMask), 99.9);
    balanceScore = min(nUnitary, nCompound);
    countScore = 0.02 .* (nUnitary + nCompound);
    grossMovementPenalty = max(0, p999 - 0.12) .* 400 + max(0, p99 - 0.05) .* 100;
    score = balanceScore + countScore - grossMovementPenalty;
    if score > bestScore
        bestScore = score;
        windowStartSec = candidateStartSec;
        windowEndSec = candidateEndSec;
    end
end
end

function LF_addAbovePeakMarkers(ax, fileContext, boutRows, subpeakTable, windowStartSec, ...
    markerOffset, yLimitTop, colorValue, displayName)
for rowIndex = 1:height(boutRows)
    row = boutRows(rowIndex, :);
    subRows = subpeakTable(string(subpeakTable.fileName) == string(row.fileName) & ...
        subpeakTable.dominantPeakIndex == row.dominantPeakIndex, :);
    for subIndex = 1:height(subRows)
        peakX = fileContext.timeSec(subRows.subpeakIndex(subIndex)) - windowStartSec;
        peakY = fileContext.motionEnvelope(subRows.subpeakIndex(subIndex));
        markerY = min(yLimitTop .* 0.96, peakY + markerOffset);
        if rowIndex == 1 && subIndex == 1
            markerVisibility = 'on';
        else
            markerVisibility = 'off';
        end
        plot(ax, peakX, markerY, '.', 'Color', colorValue, 'MarkerSize', 16, ...
            'DisplayName', displayName, 'HandleVisibility', markerVisibility);
    end
end
end

function LF_addPeakMarkers(ax, fileContext, boutRows, subpeakTable, windowStartSec, colorValue, displayName)
for rowIndex = 1:height(boutRows)
    row = boutRows(rowIndex, :);
    subRows = subpeakTable(string(subpeakTable.fileName) == string(row.fileName) & ...
        subpeakTable.dominantPeakIndex == row.dominantPeakIndex, :);
    for subIndex = 1:height(subRows)
        peakX = fileContext.timeSec(subRows.subpeakIndex(subIndex)) - windowStartSec;
        peakY = fileContext.motionEnvelope(subRows.subpeakIndex(subIndex));
        if rowIndex == 1 && subIndex == 1
            markerVisibility = 'on';
        else
            markerVisibility = 'off';
        end
        plot(ax, peakX, peakY, 'o', 'MarkerFaceColor', colorValue, ...
            'MarkerEdgeColor', 'w', 'MarkerSize', 7, ...
            'DisplayName', displayName, 'HandleVisibility', markerVisibility);
    end
end
end

function [exampleWindow, windowStartSec, windowEndSec] = LF_choosePeakOnlyWindow(fileContext, trialBouts)
settlingEndSec = 300;
windowLengthSec = 60;
stepSec = 5;
eligibleBouts = trialBouts(trialBouts.onsetTimeSec >= settlingEndSec, :);
if height(eligibleBouts) >= 5
    trialBouts = eligibleBouts;
end

startTimes = min(trialBouts.onsetTimeSec):stepSec:(max(trialBouts.onsetTimeSec) - windowLengthSec);
if isempty(startTimes)
    exampleWindow = trialBouts;
    windowStartSec = max(min(trialBouts.onsetTimeSec) - 5, min(fileContext.timeSec));
    windowEndSec = min(windowStartSec + windowLengthSec, max(fileContext.timeSec));
    return;
end

bestScore = -Inf;
bestMask = true(height(trialBouts), 1);
bestWindowStartSec = startTimes(1);
for startIndex = 1:numel(startTimes)
    windowStart = startTimes(startIndex);
    windowEnd = windowStart + windowLengthSec;
    mask = trialBouts.onsetTimeSec >= windowStart & trialBouts.onsetTimeSec <= windowEnd;
    windowRows = trialBouts(mask, :);
    if height(windowRows) < 4
        continue;
    end

    nUnitary = sum(windowRows.isUnitaryBout);
    nCompound = sum(windowRows.isCompoundBout);
    if nUnitary < 1 || nCompound < 1
        continue;
    end

    signalMask = fileContext.timeSec >= windowStart & fileContext.timeSec <= windowEnd;
    windowMax = max(fileContext.motionEnvelope(signalMask), [], 'omitnan');
    windowRange = range(fileContext.motionEnvelope(signalMask), 'omitnan');
    balanceScore = min(nUnitary, nCompound);
    countScore = nUnitary + nCompound;
    amplitudePenalty = max(0, windowMax - 0.08) .* 120;
    flatPenalty = max(0, 0.02 - windowRange) .* 100;
    score = balanceScore .* 12 + countScore - amplitudePenalty - flatPenalty;

    if score > bestScore
        bestScore = score;
        bestMask = mask;
        bestWindowStartSec = windowStart;
    end
end

exampleWindow = trialBouts(bestMask, :);
windowStartSec = bestWindowStartSec;
windowEndSec = min(bestWindowStartSec + windowLengthSec, max(fileContext.timeSec));
end

function LF_addBoutMarkers(ax, fileContext, boutTable, subpeakTable, useMinutes, timeOffsetSec, showSubpeaks)
if nargin < 6
    timeOffsetSec = 0;
end
if nargin < 7
    showSubpeaks = true;
end

unitaryRows = boutTable(boutTable.isUnitaryBout, :);
compoundRows = boutTable(boutTable.isCompoundBout, :);
unitaryColor = [0.05 0.35 0.70];
compoundColor = [0.80 0.30 0.10];

LF_plotRows(unitaryRows, unitaryColor, 'unitary onset', 'unitary peak');
LF_plotRows(compoundRows, compoundColor, 'compound onset', 'compound subpeaks');

    function LF_plotRows(rows, colorValue, onsetName, peakName)
        for rowIndex = 1:height(rows)
            row = rows(rowIndex, :);
            if useMinutes
                onsetX = fileContext.timeSec(row.onsetIndex) ./ 60;
            else
                onsetX = fileContext.timeSec(row.onsetIndex) - timeOffsetSec;
            end
            onsetY = fileContext.motionEnvelope(row.onsetIndex);
            if rowIndex == 1
                onsetVisibility = 'on';
            else
                onsetVisibility = 'off';
            end
            plot(ax, onsetX, onsetY, 'v', 'MarkerFaceColor', colorValue, ...
                'MarkerEdgeColor', colorValue, 'MarkerSize', 5, ...
                'DisplayName', onsetName, 'HandleVisibility', onsetVisibility);

            if showSubpeaks
                subRows = subpeakTable(string(subpeakTable.fileName) == string(row.fileName) & ...
                    subpeakTable.dominantPeakIndex == row.dominantPeakIndex, :);
                for subIndex = 1:height(subRows)
                    if useMinutes
                        peakX = fileContext.timeSec(subRows.subpeakIndex(subIndex)) ./ 60;
                    else
                        peakX = fileContext.timeSec(subRows.subpeakIndex(subIndex)) - timeOffsetSec;
                    end
                    peakY = fileContext.motionEnvelope(subRows.subpeakIndex(subIndex));
                    if rowIndex == 1 && subIndex == 1
                        peakVisibility = 'on';
                    else
                        peakVisibility = 'off';
                    end
                    plot(ax, peakX, peakY, 'o', 'MarkerFaceColor', colorValue, ...
                        'MarkerEdgeColor', 'w', 'MarkerSize', 5, ...
                        'DisplayName', peakName, 'HandleVisibility', peakVisibility);
                end
            end
        end
    end
end

function bestWindow = LF_chooseDetailedWindow(trialBouts)
windowLengthSec = 30;
stepSec = 3;
settlingEndSec = 300;
eligibleBouts = trialBouts(trialBouts.onsetTimeSec >= settlingEndSec, :);
if height(eligibleBouts) >= 5
    trialBouts = eligibleBouts;
end
startTimes = min(trialBouts.onsetTimeSec):stepSec:(max(trialBouts.onsetTimeSec) - windowLengthSec);
if isempty(startTimes)
    bestWindow = trialBouts;
    return;
end

bestScore = -Inf;
bestMask = true(height(trialBouts), 1);
for startIndex = 1:numel(startTimes)
    windowStart = startTimes(startIndex);
    windowEnd = windowStart + windowLengthSec;
    mask = trialBouts.onsetTimeSec >= windowStart & trialBouts.onsetTimeSec <= windowEnd;
    windowRows = trialBouts(mask, :);
    if isempty(windowRows)
        continue;
    end
    nUnitary = sum(windowRows.isUnitaryBout);
    nCompound = sum(windowRows.isCompoundBout);
    score = min(nUnitary, nCompound) .* 10 + nUnitary + nCompound;
    if score > bestScore
        bestScore = score;
        bestMask = mask;
    end
end
bestWindow = trialBouts(bestMask, :);
end
